name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.302'
    - name: Build SeaShell.Core
      run: dotnet build SeaShell.Core/SeaShell.Core.csproj --configuration Release
    - name: Build SeaShell.IO
      run: dotnet build SeaShell.IO/SeaShell.IO.csproj --configuration Release
    - name: Build SeaShell.Net
      run: dotnet build SeaShell.Net/SeaShell.Net.csproj --configuration Release
    - name: Build SeaShell.Otter
      run: dotnet build SeaShell.Otter/SeaShell.Otter.csproj --configuration Release
    - name: Build SeaShell.Reflection
      run: dotnet build SeaShell.Reflection/SeaShell.Reflection.csproj --configuration Release
    - name: Build SeaShell
      run: dotnet build SeaShell/SeaShell.csproj --configuration Release
    - name: Test with dotnet
      run: dotnet test SeaShell.Test/SeaShell.Test.csproj
